### ISSUE TITLE
ecdsa in draft -02

### ISSUE THREAD

**Issue by dthaler** [bremoran/suit-mti#7]
There seems to be a contradiction in -02.

Section 4 has:
> There are cases where this is not possible, such as suit-sha256-hsslms-ecdh-a128ctr.
> In this case, the closest equivalent profile SHOULD be used, for 
> example suit-sha256-ecdsa-ecdh-a128ctr.

However, neither suit-sha256-hsslms-ecdh-a128ctr nor suit-sha256-ecdsa-ecdh-a128ctr are defined in -02.

There is suit-sha256-hsslms-a256kw-a256ctr and suit-sha256-es256-ecdh-a128ctr however.  Perhaps those are what section 4 meant to use?

**Comment by bremoran** [comment]
Thanks for pointing this out.
I believe this section is now correct.
